name: Automated Deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    env:
      DEPLOY_REPO_NAME: ${{ secrets.DEPLOY_REPO_NAME }}
      DEPLOY_REPO_URL: ${{ secrets.DEPLOY_REPO_URL }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Commit and push changes
        run: |
          cd ./"$DEPLOY_REPO_NAME"
          git checkout main
          shopt -s extglob
          rm -r !(.git|.gitignore|.nojekyll|README.md)
          cp -R ../public/. .
          git remote set-url origin "$DEPLOY_REPO_URL"
          if [[ $(git status --porcelain) ]]; then
            git add -A
            git commit -m "Update io site."
            git push origin main
          else
            echo "No changes in 'public' folder. Skipping commit and push."
          fi